### ISSUE TITLE
URL contains wrong server

### ISSUE THREAD

**Issue by Pyanne** [jstrieb/urlpages#23]
The buttons link to a non expected url. Whatever server I use to host the script, the generated url is always beginning with "http://jstrieb.github.io/".

You can try with this one: [http://fazervrac.free.fr/urlpages/](http://fazervrac.free.fr/urlpages/)

I would expect the utl to begin with fazervrac.free.fr/urlpages/#JTBBJTN… but it begins with http://jstrieb.github.io/urlpages/#JTBBJTN

**Comment by jstrieb** [comment]
Hi! To fix this, you will need to manually modify one line of code. Specifically, [line 40 of `editor/editor.js`](https://github.com/jstrieb/urlpages/blob/fd4fbf1c70a3c7c379637875bb1e4f60940c95cf/editor/editor.js#L40) is responsible for generating the "view link." Changing the base URL there should fix your problem.

Thanks!
