### ISSUE TITLE
does this url support passing varibles with the links

### ISSUE THREAD

**Issue by therealelyayo** [jstrieb/urlpages#25]
does this url support passing varibles with the links 
example ?location=texas
thansk

**Comment by jstrieb** [comment]
This should be possible, as long as the query parameters precede the URL hash. For example:
- [Demo](https://jstrieb.github.io/urlpages/?location=texas#eyJ2ZXJzaW9uIjoiMC4yLjAiLCJjb21wcmVzc2VkIjpmYWxzZSwiYm9keSI6IlxuPCFET0NUWVBFIGh0bWw+XG48aGVhZD5cbjxzdHlsZT5cblxuPC9zdHlsZT5cbjxzY3JpcHQgdHlwZT1cInRleHQvamF2YXNjcmlwdFwiPlxud2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCBldmVudCA9PiBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwicFwiKS5pbm5lclRleHQgPSBgbG9jYXRpb249JHsobmV3IFVSTChkb2N1bWVudC5iYXNlVVJJKSkuc2VhcmNoUGFyYW1zLmdldChcImxvY2F0aW9uXCIpfWApO1xuPC9zY3JpcHQ+XG48L2hlYWQ+XG48Ym9keT5cbjxwPjwvcD5cbjwvYm9keT5cbiJ9)
- [Code](https://jstrieb.github.io/urlpages/editor/#eyJjc3MiOiIiLCJqcyI6IndpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgZXZlbnQgPT4gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcInBcIikuaW5uZXJUZXh0ID0gYGxvY2F0aW9uPSR7KG5ldyBVUkwoZG9jdW1lbnQuYmFzZVVSSSkpLnNlYXJjaFBhcmFtcy5nZXQoXCJsb2NhdGlvblwiKX1gKTsiLCJodG1sIjoiPHA+PC9wPiJ9)

**Comment by therealelyayo** [comment]
awesome this is closed if you need support am here for you
