### ISSUE TITLE
Preprocessors support?

### ISSUE THREAD

**Issue by VatsaDev** [jstrieb/urlpages#26]
# Preprocessors support?

Hi, I'm here to ask, is there anyway to add Preprocessor support?
maybe like first 9 letters after representing Preprocessors?

**Comment by jstrieb** [comment]
Hi, thanks for your question!

> Hi, I'm here to ask, is there anyway to add Preprocessor support?

Do you mean something like [this](https://developer.mozilla.org/en-US/docs/Glossary/CSS_preprocessor)?

> maybe like first 9 letters after representing Preprocessors?

Would it be possible to clarify what you mean by this second question?

**Comment by VatsaDev** [comment]
> Do you mean something like this?

yeah

> maybe like first 9 letters after representing Preprocessors?

like a url variable with three letters for each html-css-js preprocessor. then broken down and given to each editor.

im asking this, because im building an app like codepen, and i wanted to build in urlpages style 

link to project test not final - https://objective-mayer-e90967.netlify.app/

**Comment by VatsaDev** [comment]
here is the concept - [https://nostalgic-allen-1d0a0c.netlify.app/](url)
uses **url variables** not **hash**
thanks for building  _urlpages_
