### ISSUE TITLE
Safari Issues

### ISSUE THREAD

**Issue by jstrieb** [jstrieb/urlpages#9]
Something with Safari (Mojave) doesn't work. See [here](https://news.ycombinator.com/item?id=20318263).

I lack access to a device running Safari and therefore cannot replicate the issue.

**Comment by jstrieb** [comment]
[This problem](https://news.ycombinator.com/item?id=20319614) may be related, or it may be the user not understanding the application. I'm leaning towards the latter, but worth investigating if possible.

**Comment by kidGodzilla** [comment]
I took a look on the iPad Pro Safari and OSX Safari (both in the Catalina Beta) -- seems to work. 

> I don’t get anything other than a page with three text areas on iOS’s Safari.

I think the user expected something else or something more when they clicked the link.

[Imgur](https://imgur.com/ChOIblE)

[Imgur](https://imgur.com/ksRdl4v)

**Comment by jstrieb** [comment]
Thanks for taking a look! I'm going to close the issue for now.
